# This Dockerfile is for the backend API only.
FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV API_PORT=8000

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY ./api ./api

EXPOSE ${API_PORT}

CMD ["sh", "-c", "uvicorn api.main:app --host 0.0.0.0 --port $API_PORT"]