name: CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - package-name: nexa
            dockerfile: ./Dockerfile
          - package-name: nexa-api
            dockerfile: ./Dockerfile.api
          - package-name: nexa-ui
            dockerfile: ./Dockerfile.ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.package-name }}
            ghcr.io/${{ github.repository }}/${{ matrix.package-name }}
          tags: |
            type=sha,prefix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image for ${{ matrix.package-name }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    if: always()
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          if [ -f .env ]; then
            echo ".env file found"
          else
            echo ".env file not found"
          fi

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_DIR="/home/overall/vsp/multi/multi-team-dev-deployment"
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nexa-api:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nexa-ui:latest

            docker compose up -d --no-build

            echo "Deployment successful!"
